swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /paymentMethods:
    get:
      security:
        - Bearer: []
      tags:
        - Payment Method Module
      summary: Payment Method API
      description: API to get the list of all payment methods
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      responses:
        '200':
          description: Payment methods retrieved successully
          schema:
            $ref: '#/definitions/PaymentMethods'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /categories:
    get:
      security:
        - Bearer: []
      tags:
        - Categories Module
      summary: Categories API
      description: API to get all the categories
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Categories retrieved successfully
          schema:
            $ref: '#/definitions/Categories'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions/account/{idAccount}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API for fetching a transactions by account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: idAccount
          description: Account id
          required: true
      responses:
        '200':
          description: Transactions retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Invalid Fields
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
  /transactions/{idTransaction}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API to get data for a specific transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: idTransaction
          description: Transaction id
          required: true
      responses:
        '200':
          description: Transaction data retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions API
      description: API to change the category or comment of a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: idTransaction
          description: Transaction id
          required: true
        - in: body
          name: body
          description: body
          required: true
          schema:
            type: object
            properties:
              idCategory:
                type: string
              comment:
                type: string
      produces:
        - application/json
      responses:
        '200':
          description: Category or comment changed successfully
          schema:
            $ref: '#/definitions/PutTransaction'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  PaymentMethods:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            idPaymentMethod:
              type: string
            namePaymentMethod:
              type: string
  Categories:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            idCategory:
              type: string
            nameCategory:
              type: string
  Transactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            idTransaction:
              type: string
            date:
              type: string
            description:
              type: string
            amount:
              type: number
            typeTransaction:
              type: object
              properties:
                id:
                  type: string
            category:
              type: object
              properties:
                id:
                  type: string
            comment:
              type: string
  Transaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          idTransaction:
            type: string
          date:
            type: string
          description:
            type: string
          amount:
            type: number
          typeTransaction:
            type: object
            properties:
              id:
                type: string
          category:
            type: object
            properties:
              id:
                type: string
          comment:
            type: string
  PutTransaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          idTransaction:
            type: string
          idCategory:
            type: string
          comment:
            type: string
